I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/code/systems/compression.rpy", line 1, in script
    init python:
  File "game/code/systems/compression.rpy", line 1, in script
    init python:
  File "game/code/systems/compression.rpy", line 9, in <module>
    os.chdir(str(txt.name))
NotADirectoryError: [WinError 267] O nome do diretório é inválido: "D:\\Ren'Py Games\\visual-novel\\game\\images/path.txt"

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Renpy\renpy\bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "C:\Renpy\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/code/systems/compression.rpy", line 1, in script
    init python:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/code/systems/compression.rpy", line 1, in script
    init python:
  File "C:\Renpy\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Renpy\renpy\python.py", line 1052, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/code/systems/compression.rpy", line 9, in <module>
    os.chdir(str(txt.name))
NotADirectoryError: [WinError 267] O nome do diretório é inválido: "D:\\Ren'Py Games\\visual-novel\\game\\images/path.txt"

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.2.22081402
Espaço 233 1.0
Sat Oct 29 23:31:44 2022
